import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/header'
import { AuthProvider } from '@/lib/next-auth/auth-providers'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ja">
			<body>
				<AuthProvider>
					<Header />
					<main>{children}</main>
				</AuthProvider>
			</body>
		</html>
	)
}
